# Generated by Django 3.1.13 on 2021-11-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='defaultAirport',
            field=models.CharField(choices=[('ATL', 'Hartsfield-Jackson International Airport'), ('LAX', 'Los Angeles International Airport'), ('JFK', 'John F. Kennedy International Airport'), ('BOS', 'Logan International Airport'), ('MCO', 'Orlando International Airport')], default='BOS', max_length=3),
        ),
    ]
