# Generated by Django 3.1.13 on 2021-11-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_defaultairport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='defaultAirport',
            field=models.CharField(choices=[('ATL', 'Hartsfield-Jackson International Airport'), ('LAX', 'Los Angeles International Airport'), ('JFK', 'John F. Kennedy International Airport'), ('BOS', 'Logan International Airport'), ('MCO', 'Orlando International Airport')], max_length=3),
        ),
    ]
