# Generated by Django 3.1.13 on 2021-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211104_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amadeus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(max_length=3)),
                ('Dest', models.CharField(max_length=3)),
                ('Startdate', models.DateField()),
                ('Returndate', models.DateField()),
            ],
        ),
    ]
