# Generated by Django 3.1.13 on 2021-12-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_amadeus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amadeus',
        ),
    ]
