# Generated by Django 3.1.13 on 2021-12-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211209_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='defaultAirport',
            field=models.CharField(choices=[('ABE', 'Lehigh Valley International Airport (was Allentown–Bethlehem–Easton International Airport)'), ('ABI', 'Abilene Regional Airport'), ('ABQ', 'Albuquerque International Sunport'), ('ABR', 'Aberdeen Regional Airport'), ('ABY', 'Southwest Georgia Regional Airport'), ('ACK', 'Nantucket Memorial Airport'), ('ACT', 'Waco Regional Airport'), ('ACV', 'Arcata Airport')], default='BOS', max_length=3),
        ),
    ]
