# Generated by Django 3.1.13 on 2021-12-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211210_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airports',
        ),
    ]
