# Generated by Django 3.1.13 on 2021-12-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('IATAcode', models.CharField(default='BOS', max_length=3, primary_key=True, serialize=False)),
                ('Airportname', models.CharField(default='Gen. Edward Lawrence Logan International Airport', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecentRequest',
            fields=[
                ('flightOffer', models.IntegerField(default=None)),
                ('indivFlightID', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('carrierCode', models.CharField(default=None, max_length=255)),
                ('flightNum', models.IntegerField(default=None)),
                ('departureAirport', models.CharField(default=None, max_length=3)),
                ('arrivalAirport', models.CharField(default=None, max_length=3)),
                ('aircraftCode', models.CharField(default=None, max_length=3)),
                ('numOfBookableSeats', models.IntegerField(default=None)),
                ('lastTicketingDate', models.DateTimeField(default=None)),
                ('departureDate', models.DateTimeField(default=None)),
                ('departureTime', models.TimeField(default=None)),
                ('arrivalDate', models.DateTimeField(default=None)),
                ('arrivalTime', models.TimeField(default=None)),
                ('basePrice', models.FloatField(default=None)),
                ('totalPrice', models.FloatField(default=None)),
            ],
        ),
    ]
