# Generated by Django 3.1.13 on 2021-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentrequest',
            name='carrierCode',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
