# Generated by Django 3.1.13 on 2021-12-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0002_auto_20211210_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airports',
            name='myAirport',
        ),
        migrations.AddField(
            model_name='airports',
            name='Airportname',
            field=models.CharField(default='Gen. Edward Lawrence Logan International Airport', max_length=255),
        ),
        migrations.AddField(
            model_name='airports',
            name='IATAcode',
            field=models.CharField(default='BOS', max_length=3),
        ),
    ]
