# Generated by Django 3.1.13 on 2021-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0003_auto_20211210_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightOffer', models.IntegerField()),
                ('indivFlightID', models.IntegerField()),
                ('carrierCode', models.CharField(max_length=255)),
            ],
        ),
    ]
