# Generated by Django 3.1.13 on 2021-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0004_recentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentrequest',
            name='aircraftCode',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='arrivalAirport',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='arrivalDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='arrivalTime',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='basePrice',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='departureAirport',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='departureDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='departureTime',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='flightNum',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='lastTicketingDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='numOfBookableSeats',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='recentrequest',
            name='totalPrice',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='recentrequest',
            name='carrierCode',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='recentrequest',
            name='flightOffer',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recentrequest',
            name='indivFlightID',
            field=models.IntegerField(default=None),
        ),
    ]
