# Generated by Django 3.1.13 on 2021-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0005_auto_20211210_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='recentrequest',
            name='indivFlightID',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
